name: 'Terraform MLOps Stack Destroy'

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform -chdir=./terraform init
        env:
          TF_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Terraform Destroy
        id: destroy
        run: |
          terraform -chdir=./terraform destroy -auto-approve \
            -var="repo_url=https://github.com/${{ github.repository }}" \
            -var="repo_branch=${{ github.ref_name }}"
        env:
          TF_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}